name: Deploy Application

on:
  push:
    branches: [ "" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la
      shell: bash

    - name: Setup FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.futuregroup.my
        username: monaem@futuregroup.my
        password: 58!PWh1XoRd3@k
        local-dir: ./
        server-dir: /
        exclude: .gitignore
